Repository cs-select-team/CS-Select, pull requests merged in 2019-02, with the labels that each got.

#139 Add autoLogout
  src/main/resources/locale/Locale.properties
  src/main/resources/locale/Locale_de.properties
  src/main/webapp/index.jsp
  src/main/webapp/src/js/login.js
  src/main/webapp/src/js/navbar.js
Labels: enhancement

#142 tooltips for anything
  src/main/resources/locale/Locale.properties
  src/main/resources/locale/Locale_de.properties
  src/main/webapp/WEB-INF/jspf/localisation.jspf
  src/main/webapp/gamecreation.jsp
  src/main/webapp/src/js/featureDisplay.js
  src/main/webapp/src/js/organiser.js
  src/main/webapp/src/js/player.js
  src/main/webapp/src/js/playerInvite.js
  src/main/webapp/src/js/terminationCreation.js
Labels: help wanted

#194 Refactor string concatenations to template strings
  src/main/webapp/src/js/achievements.js
  src/main/webapp/src/js/alert.js
  src/main/webapp/src/js/binarySelect.js
  src/main/webapp/src/js/featureDisplay.js
  src/main/webapp/src/js/gamecreation.js
  src/main/webapp/src/js/gamemodesCreation.js
  src/main/webapp/src/js/matrixSelect.js
  src/main/webapp/src/js/organiser.js
  src/main/webapp/src/js/player.js
  src/main/webapp/src/js/playerInvite.js
  src/main/webapp/src/js/pointsDisplay.js
  src/main/webapp/src/js/streak.js
  src/main/webapp/src/js/terminationCreation.js
Labels: enhancement

#191 Gamecreation modals
  src/main/java/com/csselect/API/APIFacadeOrganiser.java
  src/main/java/com/csselect/API/httpAPI/GameManagement.java
  src/main/java/com/csselect/database/OrganiserAdapter.java
  src/main/java/com/csselect/database/mock/MockOrganiserAdapter.java
  src/main/java/com/csselect/database/mysql/MysqlOrganiserAdapter.java
  src/main/java/com/csselect/database/mysql/Query.java
  src/main/java/com/csselect/user/Organiser.java
  src/main/resources/locale/Locale.properties
  src/main/resources/locale/Locale_de.properties
  src/main/webapp/WEB-INF/jspf/localisation.jspf
  src/main/webapp/gamecreation.jsp
  src/main/webapp/src/css/main.css
  src/main/webapp/src/js/gamecreation.js
  src/main/webapp/src/js/modal.js
Labels: enhancement, invalid

#201 Update known issues section
  README.md
Labels: enhancement

#204 Use concurrent map implementations in the database
  src/main/java/com/csselect/database/mysql/MysqlDatabaseAdapter.java
  src/main/java/com/csselect/database/mysql/MysqlPlayerAdapter.java
Labels: bug
